name: flutter_tasks_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  camera: ^0.11.1
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter


  flutter_riverpod: ^2.6.1
  flutter_webrtc: ^0.12.11
  go_router: ^14.8.1
  google_mlkit_commons: ^0.9.0
  google_mlkit_face_detection: ^0.12.0
  graphql: ^5.2.0-beta.11
  graphql_flutter: ^5.2.0-beta.8
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  lottie: ^3.3.1
  riverpod: ^2.6.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/